version: '3.8'

services:
  api:
    build: api/
    volumes:
      - ./api/:/code
    ports:
      - 80:80
    environment:
      - OPENAI_CLASSIFICATION_MODEL_NAME=${OPENAI_CLASSIFICATION_MODEL_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EXAMPLE_ENV=XYZ
      - DB_URI=postgresql://postgres:postgres@postgres:5432/hackpton
    depends_on:
      - postgres
    networks:
      - hackpton

  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hackpton
    ports:
      - 5432:5432
    networks:
      - hackpton

  frontend:
    build: frontend/
    volumes:
      - /app/node_modules
      - ./frontend/:/app
    ports:
      - 3000:80
    environment:
      - PORT=80
      - REACT_APP_API_BASE_URL=${API_BASE_URL}
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - hackpton

volumes:
  postgres_data: null

networks:
  hackpton:
    name: hackpton
    driver: bridge

